FROM python:3.10-slim
WORKDIR /app
COPY weather_producer.py .
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir kafka-python requests
CMD ["python", "weather_producer.py"]

