FROM python:3.10-slim
WORKDIR /app

# Copy the stock producer script
COPY stock_producer.py .

# Install dependencies
RUN pip install --no-cache-dir kafka-python requests

# Run producer
CMD ["python", "stock_producer.py"]
