FROM python:3.10-slim
WORKDIR /app

# Copy the consumer script
COPY kafka_consumer.py .

# Install dependencies
RUN pip install --no-cache-dir kafka-python

# Run consumer
CMD ["python", "kafka_consumer.py"]
