FROM python:3.10-slim
WORKDIR /app
COPY weather_producer.py crypto_producer.py news_producer.py system_metrics_producer.py /app/
RUN pip install --no-cache-dir kafka-python requests psutil
CMD ["python", "weather_producer.py"]

